version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    # Use the Angular commit message format.
    # See:
    # - https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format
    # - https://rathbun.dev/posts/semantic-release-dependabot/
    commit-message:
      prefix:             'build'
      prefix-development: 'build'
      include:            'scope'
    open-pull-requests-limit: 20
